import React from "react";

const GlobalContext = React.createContext({
  monthIndex: 0,
  setMonthIndex: (index) => {},
  smallCalendarMonth: 0,
  setSmallCalendarMonth: (index) => {},
  daySelected: null,
  setDaySelected: (day) => {},
  showEventModal: false,
  setShowEventModal: () => {},
  dispatchCalEvent: ({ type, payload }) => {},
  savedEvents: [],
  selectedEvent: null,
  setSelectedEvent: () => {},
  setLabels: () => {},
  labels: [],
  updateLabel: () => {},
  filteredEvents: [],
  userLoggedIn: false,
  setUserLoggedIn: () => {},
  userIsPremium: false,
  setUserIsPremium: () => {},
  cardNumber: null,
  setCardNumber: () => {},
  cvc: null,
  setCvc: () => {},
  email: null,
  setEmail: () => {},
  name: null,
  setName: () => {},
  surname: null,
  setSurname: () => {},
  userName: null,
  setUserName: () => {},
  userPassword: null,
  setUserPassword: () => {},
  accountType: null,
  setAccountType: () => {},
  price: null,
  setPrice: () => {},
  userIsAdmin: false,
  setUserIsAdmin: () => {},
  currentUser: [],
  setCurrentUser: () => {},
  allUsers: [],
  setAllUsers: () => {}
});

export default GlobalContext;
